services:
  db:
    image: postgres:14
    restart: no
    environment:
      POSTGRES_USER: movie_system
      POSTGRES_PASSWORD: movie_password
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - movie_reservation_system:/var/lib/postgresql/data

volumes:
  movie_reservation_system:
    name: movie_reservation_system_data
